openapi: 3.0.3
info:
  title: Common Components API
  version: 1.0.0

paths: { }

components:
  schemas:
    Study:
      description:
        The study object containing all information and observation
        information to configure and initialize the APP
      type: object
      properties:
        active:
          description:
            The current study-state. Mainly used during the registration process.
          type: boolean
          default: true
        studyState:
          type: string
          enum:
            - active
            - preview
            - paused
            - closed
        participant:
          $ref: '#/components/schemas/SimpleParticipant'
        studyTitle:
          type: string
        participantInfo:
          type: string
        consentInfo:
          type: string
        finishText:
          type: string
        contact:
          $ref: '#/components/schemas/ContactInfo'
        start:
          type: string
          format: date
        end:
          type: string
          format: date
        observations:
          type: array
          items:
            $ref: '#/components/schemas/Observation'
          minItems: 1
        version:
          $ref: '#/components/schemas/VersionTag'
      required:
        - studyTitle
        - participantInfo
        - consentInfo
        - start
        - end
        - observations
        - version

    SimpleParticipant:
      type: object
      properties:
        id:
          type: integer
        alias:
          type: string

    ContactInfo:
      description: Contact-Information
      type: object
      properties:
        institute:
          type: string
        person:
          type: string
        email:
          type: string
        phoneNumber:
          type: string

    Observation:
      description: The configuration of an observation for the study.
      type: object
      properties:
        observationId:
          type: string
        observationType:
          type: string
        observationTitle:
          type: string
        participantInfo:
          type: string
        configuration:
          type: object
        schedule:
          type: array
          items:
            title: ObservationSchedule
            type: object
            properties:
              start:
                type: string
                format: date-time
              end:
                type: string
                format: date-time
              dataHealth:
                $ref: '#/components/schemas/DataHealthState'

        required:
          type: boolean
          default: true
        hidden:
          type: boolean
          default: false
        noSchedule:
          type: boolean
          default: false
        reminder:
          type: boolean
          default: false
        version:
          $ref: '#/components/schemas/VersionTag'
      required:
        - observationId
        - observationType
        - observationTitle
        - participantInfo
        - schedule
        - required
        - version

    VersionTag:
      description:
        A version indicator. Currently the last-modified date in EPOCH-format
        but that's not guaranteed.
      type: integer
      format: int64

    DataHealthState:
      type: string
      description: >
        Data Health states:
          * `completed` - The expected data for the observation schedule are completely availanble
          * `incomplete` - Data for the observation schedule are available and valid, but more data is expected
          * `missing` - No data for the observation schedule is available
          * `invalid` - Data is available, but the data is not valid (e.g. multiple answers for a survey; 
             wrong data format; missing required information)
      enum:
        - completed
        - incomplete
        - missing
        - invalid

    StudyConsent:
      type: object
      description: Confirms the participants consent to the study including supported observations on the device.
      properties:
        consent:
          description: Explicitly state the consent of the Participant
          type: boolean
          default: false
        deviceId:
          description: Identifier of the device used to provide consent
          type: string
        consentInfoMD5:
          description: |
            MD5-Hash of the `consentInfo` (text) the participant
            actually gave consent.
          type: string
        observations:
          type: array
          items:
            title: ObservationConsent
            type: object
            properties:
              observationId:
                type: string
              active:
                type: boolean
                default: true
            required:
              - observationId
              - active
      required:
        - consent
        - deviceId
        - consentInfoMD5
        - observations

    ApiKey:
      description: |
        Credentials for the for interacting with the backends
      type: object
      readOnly: true
      properties:
        apiId:
          type: string
          readOnly: true
        apiKey:
          type: string
          readOnly: true
      required:
        - apiId
        - apiKey

    Id:
      type: string

  responses:
    StudyInfoResponse:
      description: The Study Info
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Study'

    UnauthorizedApiKey:
      description: |
        **Authentication Required**
        Login is performed via `basic-auth` using `apiId` as username and `apiKey` as password.
