spring:
  main:
    banner-mode: off
  application:
    name: "MORE Data Gateway"
  flyway:
    # No flyway! (only required in standalone-mode)
    enabled: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DBNAME:more}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
    name: ${POSTGRES_DBNAME:more}

  session:
    store-type: redis
    redis:
      namespace: more:data-gateway:session
    timeout: PT30M

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  forward-headers-strategy: framework

more:
  gateway:
    baseUrl: ${BASE_URL:}

elastic:
  host: ${ELASTIC_HOST:localhost}
  port: ${ELASTIC_PORT:9200}
  username: ${ELASTIC_USERNAME:elastic}
  password: ${ELASTIC_PASSWORD:ctEDwSLMI-vLsQ1w+8-O}

push-notifications:
  fcm:
    google-service-json: classpath:google-services.json