spring:
  main:
    banner-mode: off
  application:
    name: "MORE Data Streams Gateway"
  flyway:
    # No flyway! (only required in standalone-mode)
    enabled: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DBNAME:more}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
    name: ${POSTGRES_DBNAME:more}

  jpa:
    hibernate:
      ddl-auto: validate

elastic:
  host: ${ELASTIC_HOST:localhost}
  port: ${ELASTIC_PORT:9200}
  username: ${ELASTIC_USERNAME:elastic}
  password: ${ELASTIC_PASSWORD:ctEDwSLMI-vLsQ1w+8-O}